### ISSUE TITLE
Unable to connect to MySQL when adding new site

### ISSUE THREAD

**Issue by ahansson89** [zach-adams/hgv-deploy-full#8]
I added one site already, now trying to add another, but I get this error:

TASK: [wordpress | Provision WP Database] ************************************\* 
failed: [everyman.dk] => {"failed": true}
msg: unable to connect, check login_user and login_password are correct, or alternatively check ~/.my.cnf contains credentials

Am I doing something wrong or what?

**Comment by dhilditch** [comment]
It's because you correctly ran the secure sql command - for additional
installs you need to modify the my.cnf file and insert your password into
that file

On 10 March 2015 at 22:57, ahansson89 notifications@github.com wrote:

> I added one site already, now trying to add another, but I get this error:
> 
> TASK: [wordpress | Provision WP Database]
> 
> ---
> 
> failed: [everyman.dk] => {"failed": true}
> msg: unable to connect, check login_user and login_password are correct,
> or alternatively check ~/.my.cnf contains credentials
> 
> Am I doing something wrong or what?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zach-adams/hgv-deploy-full/issues/8.

## 

_Dave Hilditch_
Founder
www.affiliatewebdesigners.com

Skype: davehilditch
Landline: +44 131 208 1118
Mobile/Cell: +44 7961 552 082
Twitter: @davehilditch https://twitter.com/davehilditch

**Comment by ahansson89** [comment]
I had a typo in my password.. lol :+1:
